# Numpy

In [1]:
#import numpy library

import numpy as np

In [7]:
# creating an array

arr = np.array([[1,3,5],[2,4,6]])
print(arr)

[[1 3 5]
 [2 4 6]]


In [8]:
type(arr)

numpy.ndarray

In [12]:
#to check dimension of the array

# arr.ndim
print(arr.ndim)

2


In [13]:
#to find the numbers of rows and columns

arr.shape

(2, 3)

In [15]:
onedarr = np.array([3,4,5,6])
print(onedarr)

[3 4 5 6]


In [17]:
onedarr.ndim

1

In [19]:
newarr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15] ])
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
newarr.shape

(3, 5)

In [26]:
#to find memory location in the array

print(newarr.data)

# Random number generation using numpy

In [29]:
from numpy import random

In [33]:
# (range till where you want to generate the numbers)

x = random.randint(100)
print(x)

92


In [39]:
# print 5 random numbers in range 1000

for i in range(5):
    print(random.randint(1000))

314
966
847
486
281


In [40]:
# print 5 random numbers in range 1000

i=0
while(i<5):
    print(random.randint(1000))
    i+= 1

137
231
237
991
895


In [42]:
# generate random float

k = random.rand()
print(k)

0.24768829354940614


In [46]:
for k in range(10):
    print(random.rand())

0.6608947210923896
0.2758155944791132
0.44059584901401316
0.979995517539451
0.9096509445593709
0.6283771980120118
0.02174599155537904
0.5753584531273973
0.8921866081643204
0.5165065760239798


# Generate Random Array

In [48]:
z = random.randint(10, size = (5))
print(z)

[9 3 6 7 9]


In [52]:
y = random.randint(100, size = (5,5))
print(y)

[[29 89 87  7 42]
 [56  5 35 86 55]
 [67 11 57 92 54]
 [51 76 59 60 27]
 [86 37 41  6 21]]


In [55]:
print(y.shape)
print(y.ndim)

(5, 5)
2


# Measurement of Central Tendency

In [57]:
j = random.randint(100, size = (3,3))
print(j)

#max funtion = np.amax(array name)

print("max in array :", np.amax(j))

#min funtion = np.amin(array name)

print("min in array :", np.amin(j))

[[16 79 69]
 [43 48 61]
 [77 47 46]]
max in array : 79
min in array : 16


In [68]:
# Finding Mean, Median, Standart Deviation and variance using numpy

testarr = np.array([1,2,3,4,5])
print(testarr)

#mean
print("Mean :",np.mean(testarr))

#median
print("Median :",np.median(testarr))

#Standard Deviation
print("Standard Deviation :",np.std(testarr))

#Variance
print("Variance :",np.var(testarr))


[1 2 3 4 5]
Mean : 3.0
Median : 3.0
Standard Deviation : 1.4142135623730951
Variance : 2.0


In [70]:
c = random.randint(100, size = (3,3))
print(c)

#mean
print("Mean :",np.mean(c))

#median
print("Median :",np.median(c))

#Standard Deviation
print("Standard Deviation :",np.std(c))

#Variance
print("Variance :",np.var(c))


[[92 29 44]
 [87 32 21]
 [81 96 94]]
Mean : 64.0
Median : 81.0
Standard Deviation : 29.85892756874492
Variance : 891.5555555555555


# Array broadcasting in numpy

In [66]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a+b

array([5, 7, 9])

In [67]:
a*b

array([ 4, 10, 18])